### ISSUE TITLE
Correção ortográfica

### ISSUE THREAD

**Issue by lucianohd** [CristianAmbrosi/tutoriais#2]
Na frase "Instale o visualizador **grágico** do histórico", creio que deveria ser gráfico.
Em "Podemos configurar um editor de texto padrão, para ser usado quando o Git precisar que você escreva uma menssagem." poderia ser mensagem.
Desculpe o incomodo.

**Comment by cjambrosi** [comment]
@lucianohd obrigado pelas correções.
